- bg: true
  file: forest.wav
  key: f
  name: Forest
  repeat: false
- bg: true
  file: /home/ayron/Code/soundboard/storm.wav
  key: s
  name: Storm
  repeat: true
- bg: false
  file: /home/ayron/Code/soundboard/door.wav
  key: d
  name: Door
  repeat: false
