- bg: x
  file: /home/ayron/Code/soundboard/forest.wav
  key: f
  name: Forest
  repeat: ''
- bg: x
  file: /home/ayron/Code/soundboard/storm.wav
  key: s
  name: Storm
  repeat: ''
- bg: ''
  file: /home/ayron/Code/soundboard/door.wav
  key: d
  name: Door
  repeat: ''
